# Generated by tools/gen_bootstrap_expected.R -- do not edit by hand.
#
# Characterisation expectations for the bootstrap code paths: they pin the
# RNG draw order, the aggregation and the output shape of each entry point,
# so that a change to any of them fails loudly instead of silently shifting
# users' numbers. The cases themselves live in helper-bootstrap-cases.R.
#
# All generated with set.seed(42) and boot.n = 10.

expected.bootstrap <- list(
  ci.auc.strat = list(
    class = c("ci.auc", "ci", "numeric"),
    shape = 3L,
    values = c(0.7903158875, 0.8176659892, 0.8561144986)
  ),
  ci.auc.nonstrat = list(
    class = c("ci.auc", "ci", "numeric"),
    shape = 3L,
    values = c(0.784652027, 0.8251040592, 0.8686401323)
  ),
  ci.auc.percent = list(
    class = c("ci.auc", "ci", "numeric"),
    shape = 3L,
    values = c(79.0315887534, 81.766598916, 85.6114498645)
  ),
  ci.auc.continuous = list(
    class = c("ci.auc", "ci", "numeric"),
    shape = 3L,
    values = c(0.6243309621, 0.7257791328, 0.7852007114)
  ),
  ci.auc.partial = list(
    class = c("ci.auc", "ci", "numeric"),
    shape = 3L,
    values = c(0.0214724763, 0.0323848238, 0.0443800813)
  ),
  ci.auc.conflevel = list(
    class = c("ci.auc", "ci", "numeric"),
    shape = 3L,
    values = c(0.6372120596, 0.7257791328, 0.7797510163)
  ),
  ci.auc.smooth = list(
    class = c("ci.auc", "ci", "numeric"),
    shape = 3L,
    values = c(0.498591737, 0.5718866049, 0.620589259)
  ),
  ci.auc.smooth.ns = list(
    class = c("ci.auc", "ci", "numeric"),
    shape = 3L,
    values = c(0.5652029905, 0.6193619154, 0.702802406)
  ),
  ci.se.strat = list(
    class = c("ci.se", "ci", "matrix", "array"),
    shape = c(3L, 3L),
    values = c(0.9079268293, 0.5911585366, 0.2756707317, 0.9756097561, 0.7889874353, 
      0.4146341463, 1, 0.8474847561, 0.4634146341)
  ),
  ci.se.nonstrat = list(
    class = c("ci.se", "ci", "matrix", "array"),
    shape = c(3L, 3L),
    values = c(0.923287724, 0.58796875, 0.246875, 0.9712171053, 0.8052631579, 0.4082007344, 
      1, 0.859109556, 0.5003422619)
  ),
  ci.se.percent = list(
    class = c("ci.se", "ci", "matrix", "array"),
    shape = c(3L, 3L),
    values = c(90.7926829268, 59.1158536585, 27.5670731707, 97.5609756098, 78.8987435329, 
      41.4634146341, 100, 84.7484756098, 46.3414634146)
  ),
  ci.se.smooth = list(
    class = c("ci.se", "ci", "matrix", "array"),
    shape = c(3L, 3L),
    values = c(0.8674542487, 0.4979758475, 0.111601599, 0.9131471956, 0.5980501811, 
      0.1831976809, 0.9508987998, 0.6503340438, 0.2929850261)
  ),
  ci.sp.strat = list(
    class = c("ci.sp", "ci", "matrix", "array"),
    shape = c(3L, 3L),
    values = c(1, 0.64375, 0.1239837963, 1, 0.8402777778, 0.2230902778, 1, 0.875, 0.3513888889
      )
  ),
  ci.sp.nonstrat = list(
    class = c("ci.sp", "ci", "matrix", "array"),
    shape = c(3L, 3L),
    values = c(1, 0.587191358, 0.1423444444, 1, 0.8333333333, 0.2381676413, 1, 0.9224522704, 
      0.4254663313)
  ),
  ci.sp.smooth = list(
    class = c("ci.sp", "ci", "matrix", "array"),
    shape = c(3L, 3L),
    values = c(0.9103430434, 0.4980970282, 0.0694679871, 0.9547478441, 0.6046926889, 
      0.1169337763, 0.989264538, 0.700454114, 0.1798659731)
  ),
  ci.thr.strat = list(
    class = c("ci.thresholds", "ci", "list"),
    shape = 2L,
    values = c(0.3086805556, 0.7270833333, 0.9583333333, 0.3958333333, 0.8333333333, 
      0.9722222222, 0.4704861111, 0.871875, 1, 0.693902439, 0.3201219512, 0.1817073171, 
      0.8292682927, 0.4756097561, 0.2804878049, 0.8914634146, 0.6286585366, 0.3981707317
      )
  ),
  ci.thr.nonstrat = list(
    class = c("ci.thresholds", "ci", "list"),
    shape = 2L,
    values = c(0.283, 0.7288552632, 0.9625897129, 0.3532547699, 0.8357843137, 0.9803013798, 
      0.5071594427, 0.8718245614, 1, 0.7873836436, 0.4375, 0.22578125, 0.8418650794, 
      0.5568475452, 0.2894736842, 0.9134779516, 0.6315789474, 0.3874450031)
  ),
  ci.coords.sp = list(
    class = c("ci.coords", "ci", "list"),
    shape = 2L,
    values = c(0.9079268293, 0.5911585366, 0.2756707317, 0.9756097561, 0.7889874353, 
      0.4146341463, 1, 0.8474847561, 0.4634146341, 0.3648509705, 0.4015372487, 
      0.6107069672, 0.3816793893, 0.4732874935, 0.7024793388, 0.3875236295, 0.4911209655, 
      0.7251908397)
  ),
  ci.coords.nonstrat = list(
    class = c("ci.coords", "ci", "list"),
    shape = 2L,
    values = c(0.923287724, 0.58796875, 0.246875, 0.9712171053, 0.8052631579, 0.4082007344, 
      1, 0.859109556, 0.5003422619, 0.2983638114, 0.316263705, 0.488852675, 0.3561143169, 
      0.4568322981, 0.6873643074, 0.4899207163, 0.6003503311, 0.8160486591)
  ),
  ci.coords.best = list(
    class = c("ci.coords", "ci", "list"),
    shape = 2L,
    values = c(0.4853658537, 0.6097560976, 0.7506097561, 0.7100694444, 0.8194444444, 
      0.8579861111)
  ),
  var.boot = list(
    class = "numeric",
    shape = 1L,
    values = 0.0028306028
  ),
  var.boot.ns = list(
    class = "numeric",
    shape = 1L,
    values = 0.0027372592
  ),
  var.boot.smooth = list(
    class = "numeric",
    shape = 1L,
    values = 0.0017626407
  ),
  cov.boot = list(
    class = "numeric",
    shape = 1L,
    values = -0.0008687651
  ),
  cov.boot.ns = list(
    class = "numeric",
    shape = 1L,
    values = 1.55674e-05
  ),
  roctest.boot = list(
    class = "htest",
    shape = 10L,
    values = c(1.4790202557, 0.1391349012)
  ),
  roctest.boot.ns = list(
    class = "htest",
    shape = 10L,
    values = c(1.7975749619, 0.0722443891)
  ),
  roctest.venk = list(
    class = "htest",
    shape = 9L,
    values = c(692, 0.1)
  )
)
