## Regenerate tests/testthat/helper-bootstrap-expected.R.
##
## Maintainer-only. Run from the package root with the version of pROC whose
## behaviour you want to pin already installed:
##
##     Rscript tools/gen_bootstrap_expected.R
##
## The expectations are characterisation tests: they record the RNG draw order,
## the aggregation and the output shape of every bootstrap entry point. Do not
## regenerate them to make a failing test pass -- a failure means the refactor
## changed behaviour, which is exactly what they exist to catch. Regenerate only
## when the change is intended, and say so in NEWS.
library(pROC)
data(aSAH)

testdir <- file.path("tests", "testthat")
stopifnot(dir.exists(testdir))
owd <- setwd(testdir)
on.exit(setwd(owd))

source("helper-rocs.R")
source("helper-bootstrap-cases.R")

out <- c(
  "# Generated by tools/gen_bootstrap_expected.R -- do not edit by hand.",
  "#",
  "# Characterisation expectations for the bootstrap code paths: they pin the",
  "# RNG draw order, the aggregation and the output shape of each entry point,",
  "# so that a change to any of them fails loudly instead of silently shifting",
  "# users' numbers. The cases themselves live in helper-bootstrap-cases.R.",
  "#",
  "# All generated with set.seed(42) and boot.n = 10.",
  "",
  "expected.bootstrap <- list("
)

body <- character(0)
timings <- numeric(0)
for (nm in names(bootstrap.cases)) {
  t0 <- Sys.time()
  val <- bootstrap.run(nm)
  timings[nm] <- as.numeric(difftime(Sys.time(), t0, units = "secs"))
  body <- c(body, sprintf(
    "  %s = list(\n    class = %s,\n    shape = %s,\n    values = %s\n  )",
    nm,
    paste(deparse(class(val)), collapse = ""),
    paste(deparse(bootstrap.shape(val)), collapse = ""),
    paste(deparse(round(bootstrap.sig(val), 10), width.cutoff = 70),
          collapse = "\n      ")))
}
out <- c(out, paste(body, collapse = ",\n"), ")")
writeLines(out, "helper-bootstrap-expected.R")

cat(sprintf("wrote %d cases to %s/helper-bootstrap-expected.R\n",
            length(bootstrap.cases), testdir))
cat(sprintf("total run time: %.2f s (must stay well under the CRAN budget)\n",
            sum(timings)))
print(round(sort(timings, decreasing = TRUE)[1:5], 3))
