// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/pROC.h"
#include <Rcpp.h>

using namespace Rcpp;

// bootstrapAucStratified
std::vector<double> bootstrapAucStratified(const size_t bootN, const SEXP& aROCSEXP, const SEXP& aucParamsSEXP);
RcppExport SEXP pROC_bootstrapAucStratified(SEXP bootNSEXP, SEXP aROCSEXPSEXP, SEXP aucParamsSEXPSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< const size_t >::type bootN(bootNSEXP );
        Rcpp::traits::input_parameter< const SEXP& >::type aROCSEXP(aROCSEXPSEXP );
        Rcpp::traits::input_parameter< const SEXP& >::type aucParamsSEXP(aucParamsSEXPSEXP );
        std::vector<double> __result = bootstrapAucStratified(bootN, aROCSEXP, aucParamsSEXP);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// bootstrapAucNonStratified
std::vector<double> bootstrapAucNonStratified(const size_t bootN, const SEXP& aROCSEXP, const SEXP& aucParamsSEXP);
RcppExport SEXP pROC_bootstrapAucNonStratified(SEXP bootNSEXP, SEXP aROCSEXPSEXP, SEXP aucParamsSEXPSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< const size_t >::type bootN(bootNSEXP );
        Rcpp::traits::input_parameter< const SEXP& >::type aROCSEXP(aROCSEXPSEXP );
        Rcpp::traits::input_parameter< const SEXP& >::type aucParamsSEXP(aucParamsSEXPSEXP );
        std::vector<double> __result = bootstrapAucNonStratified(bootN, aROCSEXP, aucParamsSEXP);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// delongPlacementsCpp
List delongPlacementsCpp(List roc);
RcppExport SEXP pROC_delongPlacementsCpp(SEXP rocSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< List >::type roc(rocSEXP );
        List __result = delongPlacementsCpp(roc);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// computeSeSpList
List computeSeSpList(const NumericVector& thresholds, const NumericVector& controls, const NumericVector& cases, const std::string& direction);
RcppExport SEXP pROC_computeSeSpList(SEXP thresholdsSEXP, SEXP controlsSEXP, SEXP casesSEXP, SEXP directionSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< const NumericVector& >::type thresholds(thresholdsSEXP );
        Rcpp::traits::input_parameter< const NumericVector& >::type controls(controlsSEXP );
        Rcpp::traits::input_parameter< const NumericVector& >::type cases(casesSEXP );
        Rcpp::traits::input_parameter< const std::string& >::type direction(directionSEXP );
        List __result = computeSeSpList(thresholds, controls, cases, direction);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// computeAuc
double computeAuc(const Rcpp::List& aROCList, const Rcpp::List& aucParamsList);
RcppExport SEXP pROC_computeAuc(SEXP aROCListSEXP, SEXP aucParamsListSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< const Rcpp::List& >::type aROCList(aROCListSEXP );
        Rcpp::traits::input_parameter< const Rcpp::List& >::type aucParamsList(aucParamsListSEXP );
        double __result = computeAuc(aROCList, aucParamsList);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// computeAucSeSp
double computeAucSeSp(const std::vector<double>& se, const std::vector<double>& sp, const Rcpp::List& aucParamsList);
RcppExport SEXP pROC_computeAucSeSp(SEXP seSEXP, SEXP spSEXP, SEXP aucParamsListSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< const std::vector<double>& >::type se(seSEXP );
        Rcpp::traits::input_parameter< const std::vector<double>& >::type sp(spSEXP );
        Rcpp::traits::input_parameter< const Rcpp::List& >::type aucParamsList(aucParamsListSEXP );
        double __result = computeAucSeSp(se, sp, aucParamsList);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// runit_Predictor_bracketOperator
NumericVector runit_Predictor_bracketOperator(const Rcpp::NumericVector& someControls, const Rcpp::NumericVector& someCases, const int i);
RcppExport SEXP pROC_runit_Predictor_bracketOperator(SEXP someControlsSEXP, SEXP someCasesSEXP, SEXP iSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type someControls(someControlsSEXP );
        Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type someCases(someCasesSEXP );
        Rcpp::traits::input_parameter< const int >::type i(iSEXP );
        NumericVector __result = runit_Predictor_bracketOperator(someControls, someCases, i);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// runit_Predictor_bracketOperatorVector
NumericVector runit_Predictor_bracketOperatorVector(const Rcpp::NumericVector& someControls, const Rcpp::NumericVector& someCases);
RcppExport SEXP pROC_runit_Predictor_bracketOperatorVector(SEXP someControlsSEXP, SEXP someCasesSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type someControls(someControlsSEXP );
        Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type someCases(someCasesSEXP );
        NumericVector __result = runit_Predictor_bracketOperatorVector(someControls, someCases);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// runit_Predictor_getOrder
IntegerVector runit_Predictor_getOrder(const Rcpp::NumericVector& someControls, const Rcpp::NumericVector& someCases);
RcppExport SEXP pROC_runit_Predictor_getOrder(SEXP someControlsSEXP, SEXP someCasesSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type someControls(someControlsSEXP );
        Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type someCases(someCasesSEXP );
        IntegerVector __result = runit_Predictor_getOrder(someControls, someCases);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// runit_Predictor_getControls
NumericVector runit_Predictor_getControls(const Rcpp::NumericVector& someControls, const Rcpp::NumericVector& someCases);
RcppExport SEXP pROC_runit_Predictor_getControls(SEXP someControlsSEXP, SEXP someCasesSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type someControls(someControlsSEXP );
        Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type someCases(someCasesSEXP );
        NumericVector __result = runit_Predictor_getControls(someControls, someCases);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// runit_Predictor_getCases
NumericVector runit_Predictor_getCases(const Rcpp::NumericVector& someControls, const Rcpp::NumericVector& someCases);
RcppExport SEXP pROC_runit_Predictor_getCases(SEXP someControlsSEXP, SEXP someCasesSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type someControls(someControlsSEXP );
        Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type someCases(someCasesSEXP );
        NumericVector __result = runit_Predictor_getCases(someControls, someCases);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// runit_Predictor_isControl
bool runit_Predictor_isControl(const Rcpp::NumericVector& someControls, const Rcpp::NumericVector& someCases, const int i);
RcppExport SEXP pROC_runit_Predictor_isControl(SEXP someControlsSEXP, SEXP someCasesSEXP, SEXP iSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type someControls(someControlsSEXP );
        Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type someCases(someCasesSEXP );
        Rcpp::traits::input_parameter< const int >::type i(iSEXP );
        bool __result = runit_Predictor_isControl(someControls, someCases, i);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// runit_Predictor_isCase
bool runit_Predictor_isCase(const Rcpp::NumericVector& someControls, const Rcpp::NumericVector& someCases, const int i);
RcppExport SEXP pROC_runit_Predictor_isCase(SEXP someControlsSEXP, SEXP someCasesSEXP, SEXP iSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type someControls(someControlsSEXP );
        Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type someCases(someCasesSEXP );
        Rcpp::traits::input_parameter< const int >::type i(iSEXP );
        bool __result = runit_Predictor_isCase(someControls, someCases, i);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
