# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

bootstrapAucStratified <- function(bootN, aROCSEXP, aucParamsSEXP) {
    .Call('pROC_bootstrapAucStratified', PACKAGE = 'pROC', bootN, aROCSEXP, aucParamsSEXP)
}

bootstrapAucNonStratified <- function(bootN, aROCSEXP, aucParamsSEXP) {
    .Call('pROC_bootstrapAucNonStratified', PACKAGE = 'pROC', bootN, aROCSEXP, aucParamsSEXP)
}

delongPlacementsCpp <- function(roc) {
    .Call('pROC_delongPlacementsCpp', PACKAGE = 'pROC', roc)
}

computeSeSpList <- function(thresholds, controls, cases, direction) {
    .Call('pROC_computeSeSpList', PACKAGE = 'pROC', thresholds, controls, cases, direction)
}

computeAuc <- function(se, sp, aucParamsList) {
    .Call('pROC_computeAuc', PACKAGE = 'pROC', se, sp, aucParamsList)
}

